---
title: "R Notebook"
output: html_notebook
---

```{r}

library(tidyverse)
library(janitor)
library(GGally)
library(modelr)
library(pROC)
library(broom)
library(caret)
library(rpart)
library(yardstick)
library(rpart.plot)

```


```{r}

titanic_set <- read_csv('data/titanic_decision_tree_data.csv') %>% clean_names()

shuffle_index <- sample(1:nrow(titanic_set))

# shuffle the data so class order isn't in order - need this for training/testing split later on 
titanic_set <- titanic_set[shuffle_index, ]
```


```{r}
titanic_clean <- titanic_set %>% 
  select(-c(x1, passenger_id, name, ticket, fare, cabin)) %>% 
  drop_na(survived) %>% 
  mutate(across(c(sex, survived, pclass, embarked), as.factor),
         age = as.factor(if_else(age < 17, "child", "adult"))) %>% 
  drop_na() %>% 
  select(survived, everything())
  
```

```{r}
titanic_clean %>% 
  ggpairs()

# class and sex look important
```




```{r}
n_data <- nrow(titanic_clean)

test_index <- sample(1:n_data, size = n_data * 0.2)

titanic_test <- titanic_clean %>%  slice(test_index)

titanic_train <- titanic_clean %>% slice(-test_index)

titanic_test %>% 
  janitor::tabyl(survived)

titanic_train %>% 
  janitor::tabyl(survived)

# close enough balance
```

```{r}
titanic_fit <- rpart(
  formula = survived ~ .,
  data = titanic_train,
  method = "class"
)

rpart.plot(titanic_fit,
           yesno = 2,
           fallen.leaves = TRUE,
           faclen = 6,
           digits = 4)

# note the interpretation below is only valid for the first time i ran this code

# the three import variables are sex, class and embarked
# males were least likely to survive and their chance were not impacted significantly by any of the other factors.
# females were more likely to die if they were third class and even more so if the embarked in southhampton 
# first and second class women were the least likely to die
```



```{r}
library(modelr)

titanic_test_pred <- titanic_test %>% 
  add_predictions(titanic_fit, type = "class")



titanic_test_pred
```

```{r}
library(yardstick)

conf_mat <- titanic_test_pred %>% 
  conf_mat(truth = survived,
           estimate = pred)

conf_mat

# the model has a lot of false poitives where people have been predicted to have died but actually survived 
```

```{r}
accuracy <- titanic_test_pred %>% 
  accuracy(truth = survived,
           estimate = pred)

accuracy

#75% accuracy

confusionMatrix(titanic_test_pred$pred, titanic_test_pred$survived)
```

```{r}
library(ranger)
```


```{r}
rf_classifier <- ranger(survived ~ ., 
                        data = titanic_train, 
                        importance = "impurity", 
                        num.trees = 5000, 
                        mtry = 1, 
                        min.node.size = 1,
                        splitrule = "extratrees"
                        )

rf_classifier
```

```{r}
importance(rf_classifier)
```

```{r}
titanic_pred <- titanic_test %>%
  mutate(pred = predict(rf_classifier, data = titanic_test)$predictions)
```

```{r}
confusionMatrix(titanic_pred$pred, titanic_pred$survived)
```

```{r}
?ranger
?trainControl
?expand.grid
```

```{r}
control <- trainControl(
  method = "repeatedcv", 
  number = 5, 
  repeats = 10
)

tune_grid = expand.grid(
  mtry = 1:6,
  splitrule = c("gini", "extratrees"),
  min.node.size = c(1, 3, 5)
)




```

```{r}
rf_tune <- train(
  survived ~ ., 
  data = titanic_train, 
  method = "ranger",
  metric = "Kappa",
  num.trees = 1000,
  importance = "impurity",
  tuneGrid = tune_grid, 
  trControl = control
)

plot(rf_tune)
rf_tune
```

